version: '3'

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    container_name: antlia-api
    env_file:
      - .env
    environment:
      DATABASE_URL: "${DATABASE_URL}"
    ports:
      - 80:3000
    restart: always