FROM node:18.16-slim 

LABEL maintainer="Thiago Alves <thiago_marketingdigital@hotmail.com>"

WORKDIR /usr/src/app

COPY package*.json ./

RUN apt update -y && apt install -y openssl

RUN npm install -g pnpm

COPY . .

RUN npx prisma generate

RUN npx prisma migrate deploy

RUN pnpm run build

EXPOSE 3000

CMD [ "node", "dist/main.js" ]