version: '3.1'

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    container_name: antlia-api
    env_file:
      - .env.prod
    ports:
      - 80:3000
    restart: always
