version: '3.1'

services:
  api:
    build: .
    image: ghcr.io/projeto-antlia/antlia-core-api:latest
    container_name: antlia-api
    env_file:
      - .env.prod
    ports:
      - 80:3000
    restart: always
