name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  deploy:
    runs-on: self-hosted

    steps:
    - name: Login to Github Container Registry
      run: echo ${{ secrets.GH_PACKAGES_TOKEN }} | docker login ghcr.io -u "${{ secrets.GH_PACKAGES_USER }}" --password-stdin

    - name: Delete Old Docker Container
      run: docker-compose stop && docker-compose rm -f

    - name: Pull Docker Image
      run: docker-compose pull

    - name: Run Docker Container
      run: docker-compose up -d