name: CI Pipeline

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: azure/docker-login@v1
        with: 
          login-server: ghcr.io
          username: ${{ secrets.GH_PACKAGES_USER }}
          password: ${{ secrets.GH_PACKAGES_TOKEN }}

      - name: Build Dockerfile
        run: |
          docker build -t ghcr.io/projeto-antlia/antlia-core-api:latest .

      - name: Push Image
        run: |
          docker push ghcr.io/projeto-antlia/antlia-core-api:latest

